"""Configured benchmark families with stable, descriptive constructors."""

from ..baker import BakerPanelConfig, baker, baker_design
from ..canonical import (
    CanonicalPanelConfig,
    available_canonical_designs,
    classic_factor,
    classic_factor_design,
    factor_synthetic,
    factor_synthetic_design,
    make_canonical,
    mixed_factor,
    mixed_factor_design,
    synthetic_control,
    synthetic_control_design,
    time_series,
    time_series_design,
    weak_factor,
    weak_factor_design,
)
from ..ftest import (
    FTestCohortConfig,
    FTestTemporalConfig,
    available_ftest_cohort_designs,
    available_ftest_temporal_designs,
    ftest_cohort,
    ftest_cohort_design,
    ftest_cohort_profiles,
    ftest_temporal,
    ftest_temporal_design,
    ftest_temporal_profile,
)
from .att_dml import (
    ATTDMClusteredConfig,
    ATTDMConditionalConfig,
    ATTDMLatentConfig,
    att_dml,
    att_dml_design,
    available_att_dml_designs,
)
from .gsynth import GSynthCompositeConfig, gsynth_composite, gsynth_composite_design
from .lepskii import (
    LepskiiPanelConfig,
    available_lepskii_designs,
    lepskii,
    lepskii_design,
    lepskii_profiles,
)
from .regression_compression import (
    AnscombePanelConfig,
    RegressionCompressionConfig,
    anscombe,
    anscombe_design,
    available_anscombe_designs,
    regression_compression,
    regression_compression_design,
)

__all__ = [
    "ATTDMClusteredConfig",
    "ATTDMConditionalConfig",
    "ATTDMLatentConfig",
    "AnscombePanelConfig",
    "BakerPanelConfig",
    "CanonicalPanelConfig",
    "FTestCohortConfig",
    "FTestTemporalConfig",
    "GSynthCompositeConfig",
    "LepskiiPanelConfig",
    "RegressionCompressionConfig",
    "anscombe",
    "anscombe_design",
    "att_dml",
    "att_dml_design",
    "available_anscombe_designs",
    "available_att_dml_designs",
    "available_canonical_designs",
    "available_ftest_cohort_designs",
    "available_ftest_temporal_designs",
    "available_lepskii_designs",
    "baker",
    "baker_design",
    "classic_factor",
    "classic_factor_design",
    "factor_synthetic",
    "factor_synthetic_design",
    "ftest_cohort",
    "ftest_cohort_design",
    "ftest_cohort_profiles",
    "ftest_temporal",
    "ftest_temporal_design",
    "ftest_temporal_profile",
    "gsynth_composite",
    "gsynth_composite_design",
    "lepskii",
    "lepskii_design",
    "lepskii_profiles",
    "make_canonical",
    "mixed_factor",
    "mixed_factor_design",
    "regression_compression",
    "regression_compression_design",
    "synthetic_control",
    "synthetic_control_design",
    "time_series",
    "time_series_design",
    "weak_factor",
    "weak_factor_design",
]
