"""Composable, estimator-neutral simulation infrastructure for panel data."""

from .canonical import (
    CanonicalPanelConfig,
    ClassicFactorOutcome,
    FactorSyntheticOutcome,
    MixedFactorOutcome,
    PanelConfig,
    PanelData,
    SyntheticControlOutcome,
    TimeSeriesOutcome,
    WeakFactorOutcome,
    available_canonical_designs,
    canonical_registry,
    classic_factor,
    classic_factor_design,
    factor_synthetic,
    factor_synthetic_design,
    make_canonical,
    mixed_factor,
    mixed_factor_design,
    synthetic_control,
    synthetic_control_design,
    time_series,
    time_series_design,
    weak_factor,
    weak_factor_design,
)
from .components import (
    AssignmentModel,
    CallableOutcomeModel,
    ComponentDraw,
    ConstantEffect,
    EffectModel,
    LinearRampEffect,
    OutcomeModel,
    PanelDimensions,
    SimulationContext,
    SingleCohortAssignment,
    StaggeredAdoption,
)
from .data import PanelDataset
from .registry import DGPRegistry
from .simulator import PanelSimulator, resolve_rng

__version__ = "0.1.0"

__all__ = [
    "AssignmentModel",
    "CallableOutcomeModel",
    "CanonicalPanelConfig",
    "ClassicFactorOutcome",
    "ComponentDraw",
    "ConstantEffect",
    "DGPRegistry",
    "EffectModel",
    "FactorSyntheticOutcome",
    "LinearRampEffect",
    "MixedFactorOutcome",
    "OutcomeModel",
    "PanelConfig",
    "PanelData",
    "PanelDataset",
    "PanelDimensions",
    "PanelSimulator",
    "SimulationContext",
    "SingleCohortAssignment",
    "StaggeredAdoption",
    "SyntheticControlOutcome",
    "TimeSeriesOutcome",
    "WeakFactorOutcome",
    "available_canonical_designs",
    "canonical_registry",
    "classic_factor",
    "classic_factor_design",
    "factor_synthetic",
    "factor_synthetic_design",
    "make_canonical",
    "mixed_factor",
    "mixed_factor_design",
    "resolve_rng",
    "synthetic_control",
    "synthetic_control_design",
    "time_series",
    "time_series_design",
    "weak_factor",
    "weak_factor_design",
]
